### PR TITLE
fixed sign in page #5, added links for root and sign in

### LINKED ISSUE #5: login (views)
Components:
- [x] navbar #3 
- [x] login form #21

### PR DESCRIPTION
**Pull request by te4-alexander-kjellberg1**
## What issue did you implement or fix?
Fixed #5 

## Summary
- Fixed sign in page with its proper components
- Added links to root and sign in

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How can this implementation be improved?
- Sign in form could be a view, it does not really make sense that it is a component

### CODE REVIEW

File: vue/src/components/NavBar.vue [hunk 1]
```diff
@@ -54,18 +59,24 @@
         cols="1"
         class="pa-0 d-flex justify-center align-center"
         style="height:100%"
-
+        
         >
             <v-btn 
             style="border-radius: 0px; height:100%; width:100%"
```
Comment (itggot-linus-styren) [inline vue/src/components/NavBar.vue:65]: Setting border radius to 0 can be done by https://vuetifyjs.com/en/styles/border-radius/#removing-border-radius
Also using width and height in style attributed is not recommended. Instead try adding a v-container add use fluid and fill-height: https://stackoverflow.com/a/51181875/3013334

Recommended to read https://vuetifyjs.com/en/components/grids/#usage

File: vue/src/components/NavBar.vue [hunk 2]
```diff
@@ -54,18 +59,24 @@
...
             elevation="0"
             >
-                <v-icon
-                class="mr-2"
+                <router-link
+                    style="text-decoration: none; color:black;"
```
Comment (itggot-linus-styren) [inline vue/src/components/NavBar.vue:69]: To avoid inline css, an alternative could be to use v-btn and pass the "to" prop: https://stackoverflow.com/a/46318697/3013334

**Review by itggot-linus-styren — COMMENTED** [review]
Another example of a code review. Some suggestions to consider for better maintainability. Try to avoid using inline css even if vuetify enforces you to do this for router-link.

**Review by Te4-Jacob-sandstrom — APPROVED** [review]
